"""Static isolation rules for provider SDKs, tokens, bot registry, and i18n."""

from __future__ import annotations

import ast
from collections.abc import Iterator
from pathlib import Path

import pytest

BACKEND_ROOT = Path(__file__).resolve().parents[2]
SOURCE_ROOT = BACKEND_ROOT / "src" / "app"
MODULES_ROOT = SOURCE_ROOT / "modules"
_APPROVED_SECRET_RESOLVERS = {
    SOURCE_ROOT / "core" / "config" / "settings.py",
    SOURCE_ROOT / "core" / "bots" / "settings.py",
    SOURCE_ROOT / "infrastructure" / "bots" / "telegram" / "factory.py",
    SOURCE_ROOT / "infrastructure" / "bots" / "telegram" / "verifier.py",
}


def _python_files(root: Path) -> Iterator[Path]:
    """Yield Python files without generated bytecode folders."""

    yield from sorted(path for path in root.rglob("*.py") if "__pycache__" not in path.parts)


def _imports(path: Path) -> set[str]:
    """Return absolute imports for one source file."""

    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    result: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            result.update(alias.name for alias in node.names)
        elif isinstance(node, ast.ImportFrom) and node.level == 0 and node.module is not None:
            result.add(node.module)
    return result


def _layer_files(layer: str) -> Iterator[Path]:
    """Yield a future module's layer files when that layer exists."""

    for module_directory in MODULES_ROOT.iterdir():
        candidate = module_directory / layer
        if module_directory.is_dir() and candidate.is_dir():
            yield from _python_files(candidate)


def _forbidden(path: Path, prefixes: tuple[str, ...]) -> set[str]:
    """Find imports at or beneath a forbidden package prefix."""

    return {
        imported
        for imported in _imports(path)
        if any(imported == prefix or imported.startswith(f"{prefix}.") for prefix in prefixes)
    }


@pytest.mark.architecture
def test_domain_and_application_cannot_depend_on_bots_or_i18n_implementation() -> None:
    """Business layers remain independent from provider SDK and localization runtime types."""

    prohibited = ("aiogram", "fastapi", "starlette", "app.infrastructure.bots", "app.core.i18n")
    for layer in ("domain", "application"):
        for path in _layer_files(layer):
            violations = _forbidden(path, prohibited)
            assert not violations, (
                f"{path.relative_to(BACKEND_ROOT)} imports forbidden packages: {sorted(violations)}"
            )


@pytest.mark.architecture
def test_modules_cannot_import_bot_infrastructure_or_foreign_presentation() -> None:
    """Module code receives pre-bound contracts, not global or foreign bot surfaces."""

    violations: list[str] = []
    for module_directory in MODULES_ROOT.iterdir():
        if not module_directory.is_dir() or module_directory.name.startswith("_"):
            continue
        current_module = module_directory.name
        for path in _python_files(module_directory):
            for imported in _imports(path):
                if imported == "app.infrastructure.bots" or imported.startswith(
                    "app.infrastructure.bots."
                ):
                    violations.append(f"{path.relative_to(BACKEND_ROOT)} imports {imported}")
                parts = imported.split(".")
                if (
                    len(parts) >= 4
                    and parts[:2] == ["app", "modules"]
                    and parts[2] != current_module
                    and parts[3] in {"presentation", "locales"}
                ):
                    violations.append(f"{path.relative_to(BACKEND_ROOT)} imports {imported}")
    assert not violations, "Module bot/i18n isolation violations: " + "; ".join(violations)


@pytest.mark.architecture
def test_raw_secret_resolution_stays_in_approved_security_and_factory_files() -> None:
    """Token and webhook secrets cannot be read by modules or generic handlers."""

    violations: list[str] = []
    for path in _python_files(SOURCE_ROOT):
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        if (
            any(
                isinstance(node, ast.Attribute) and node.attr == "get_secret_value"
                for node in ast.walk(tree)
            )
            and path not in _APPROVED_SECRET_RESOLVERS
        ):
            violations.append(str(path.relative_to(BACKEND_ROOT)))
    assert not violations, "Unapproved raw secret resolution: " + ", ".join(violations)


@pytest.mark.architecture
def test_public_module_contracts_cannot_export_telegram_sdk_types() -> None:
    """A future module's public API remains provider-neutral."""

    violations: list[str] = []
    for module_directory in MODULES_ROOT.iterdir():
        public_contract = module_directory / "public.py"
        if public_contract.is_file() and _forbidden(public_contract, ("aiogram",)):
            violations.append(str(public_contract.relative_to(BACKEND_ROOT)))
    assert not violations, "Telegram SDK leaked into public module contracts: " + ", ".join(
        violations
    )
